materials:
  - TNT
time: 30
events: false

spawn:
  world: world
  x: 0
  y: 70
  z: 0

arenas:
  main:
    name: MAIN
    location:
      world: world
      x: 0
      y: 70
      z: 0
    players: 16

